network: "SATRN"
charset: "./resources/charset.txt"
resize_hw:
  height: 32
  width: 100
use_rgb: False
label_maxlen: 25
seed: 42
model_dir: "/content/drive/MyDrive/saved_models/satrn_2"

hidden_size: 512
filter_size: 2048
enc_layers: 12
dec_layers: 6
num_heads: 8
dropout_rate: 0.9 
rot_stddev: 0.6

train:
  dataset_paths:
      - "../data/train/ai_hub-words-*.tfrecord"     # 9M   mjsynth train+valid+test
  dataset_portions:
    - 1
  lowercase: False
  alphanumeric: False
  batch_size: 64
  num_threads: 8
  tune_from: ""
  max_num_steps: 100001
  verbose: False
  save_steps: 5000
  summary_steps: 1000
  optimizer:
    optimizer: 'Adam'
    learning_rate: 0.0003
    beta2: 0.999
    use_clr: True
    clr_step: 250000
    grad_clip_norm: 2.

valid:
  dataset_paths:
      - "../data/valid/gt_valid.txt"

  lowercase: False
  alphanumeric: False
  batch_size: 64
  steps: 1000

eval:
  dataset_paths: 
      - "../data/test/gt_test.txt"
  lowercase: False
  alphanumeric: False
  model_path: "/content/drive/MyDrive/saved_models/satrn_2"
  batch_size: 64
  verbose: False

